#!/bin/bash

###OLDCONF=$(dpkg -l|grep "^rc"|awk '{print $2}')
CURKERNEL=$(uname -r|sed 's/-*[a-z]//g'|sed 's/-386//g')
LINUXPKG="linux-(image|headers|ubuntu-modules|restricted-modules)"
###OLDKERNELS=$(dpkg -l|awk '{print $2}'|grep -E $LINUXPKG |grep -vE $ME>
#Set Yellow color for script messages
YELLOW="\033[1;33m"
#Set Red color for script messages
RED="\033[0;31m"
#End color on colored for script message
ENDCOLOR="\033[0m"
#Homebrew, (The package manager for MacOS) can't be run as root. This variable runs helps run commands as the original user
NONSUDOUSER=$(echo $(logname))

#Open Superuser prompt
if [ $USER != root ]; then
  echo -e $RED"Error: must be root"
  echo -e $YELLOW"Exiting..."$ENDCOLOR
  exit 0
fi

#Set script variables
FILE_APT=/usr/bin/apt
FILE_APTGET=/usr/bin/apt-get
FILE_APTITUDE=/usr/bin/aptitude
###FILE_ATOM=/usr/bin/atom
###FILE_BETTERDISCORDCTL=/usr/local/bin/betterdiscordctl
FILE_BREW=/opt/homebrew/bin/brew
FILE_CARGO=/usr/bin/cargo
FILE_DORELEASEUPGRADE=/usr/bin/do-release-upgrade
FILE_DPKG=/usr/bin/dpkg
FILE_FLATPAK=/usr/bin/flatpak
FILE_FWUPDMGR=/usr/bin/fwupdmgr
FILE_LIBREGAMING=/home/$USER/.local/bin/LibreGaming
FILE_NPM=/usr/bin/npm
FILE_PACMAN=/usr/bin/pacman
###FILE_PIP3=/usr/local/bin/pip3
FILE_POPUPGRADE=/usr/bin/pop-upgrade
FILE_SNAP=/usr/bin/snap
###FILE_TLDR=/usr/bin/tldr
FILE_UPDATEGRUB=/usr/sbin/update-grub
FILE_UPDATEGRUB2=/usr/sbin/update-grub2
FILE_ZKG=/usr/bin/zkg
###FILE_ZSH="$ZSH"
###FILE_ZSH=/usr/bin/zsh

#Fix broken packages (DPKG)
if test -f "$FILE_DPKG"; then
    echo -e $YELLOW"Fixing broken packages (DPKG)..."$ENDCOLOR
    dpkg --configure -a
fi

#Fetch update data (APT)
if test -f "$FILE_APTGET"; then
    echo -e $YELLOW"Fetching update data (APT)..."$ENDCOLOR
    apt-get -qq update -y
fi

#Fetch update data (BREW)
if test -f "$FILE_BREW"; then
    echo -e $YELLOW"Fetching update data (BREW)..."$ENDCOLOR
    sudo -u $NONSUDOUSER brew update | grep --color=never updated
fi

#Fetch update data (PACMAN / YAY)
if test -f "$FILE_PACMAN"; then
  if command -v yay &> /dev/null; then
    echo -e $YELLOW"Fetching update data (YAY)..."$ENDCOLOR
    sudo -u $NONSUDOUSER yay -Syy --noconfirm 1>/dev/null
  else
    echo -e $YELLOW"Fetching update data (PACMAN)..."$ENDCOLOR
    pacman -Syy --noconfirm 1>/dev/null
  fi
fi

#Apply updates and fix various system things (APT)
if test -f "$FILE_APTGET"; then
    echo -e $YELLOW"Updating packages (APT)..."$ENDCOLOR
    apt-get -qq dist-upgrade -y
    apt-get -qq --fix-missing --fix-broken install -y
fi

#Apply updates (BREW)
if test -f "$FILE_BREW"; then
    echo -e $YELLOW"Updating packages (BREW)..."$ENDCOLOR
    sudo -u $NONSUDOUSER brew upgrade
fi

#Apply updates (PACMAN / YAY)
if test -f "$FILE_PACMAN"; then
  if command -v yay &> /dev/null; then
    echo -e $YELLOW"Updating packages (YAY)..."$ENDCOLOR
    sudo -u $NONSUDOUSER yay -Syu --noconfirm 1>/dev/null ##Doesn't show any packages or progress. Need to fix ASAP
  else
    echo -e $YELLOW"Updating packages (PACMAN)..."$ENDCOLOR
    pacman -Syu --noconfirm 1>/dev/null ##Doesn't show any packages or progress. Need to fix ASAP
  fi
fi

#Scan/Repair grub
if test -f "$FILE_UPDATEGRUB"; then
    echo -e $YELLOW"Scanning/Repairing grub..."$ENDCOLOR
    update-grub 2>/dev/null

    #Scan/Repair grub 2
    if test -f "$FILE_UPDATEGRUB2"; then
        echo -e $YELLOW"Scanning/Repairing grub 2..."$ENDCOLOR
        update-grub2 2>/dev/null
    fi
fi

#Find and update firmware
if test -f "$FILE_FWUPDMGR"; then
    echo -e $YELLOW"Looking for newest firmware updates..."$ENDCOLOR
    fwupdmgr get-devices >/dev/null
    fwupdmgr refresh --force >/dev/null 2>&1
    fwupdmgr get-updates 2>/dev/null
    fwupdmgr update 2>/dev/null
fi

#Update omz if omz is installed (Currently not working)
##maybe use "sudo -u $NONSUDOUSER"???
##Figure out way to run below line as nonsudouser
###if command -v /home/$NONSUDOUSER/.oh-my-zsh/tools/upgrade.sh &> /dev/null
###then
###    echo -e $YELLOW"Updating omz..."$ENDCOLOR
###    ##omz update 2>/dev/null
###    chmod +x /home/$NONSUDOUSER/.oh-my-zsh/tools/upgrade.sh
###    sudo -u $NONSUDOUSER /home/$NONSUDOUSER/.oh-my-zsh/tools/upgrade.sh ##Still shows "Applied autostash." No matter what. Fix this
###fi

#Upgrade to latest version (only works on Pop! OS)
if test -f "$FILE_POPUPGRADE"; then
    echo -e $YELLOW"Finding Newest 'Pop! OS' release..."$ENDCOLOR
    pop-upgrade release upgrade >/dev/null
fi

#Upgrade to latest version (only works on Ubuntu)
if test -f "$FILE_DORELEASEUPGRADE"; then
    echo -e $YELLOW"Finding Newest 'Ubuntu' release..."$ENDCOLOR
    do-release-upgrade >/dev/null
fi

#Update Flatpaks if flatpak is Installed
if test -f "$FILE_FLATPAK"; then
    echo -e $YELLOW"Updating Flatpaks..."$ENDCOLOR
    flatpak update >/dev/null
fi

#Update Snaps if snapd is Installed
if test -f "$FILE_SNAP"; then
    echo -e $YELLOW"Updating Snaps..."$ENDCOLOR
    snap refresh >/dev/null
fi

#Update npm if npm is installed
if test -f "$FILE_NPM"; then
    echo -e $YELLOW"Updating npm packages..."$ENDCOLOR
    npm update >/dev/null
fi

#Update Rust Packages if cargo is installed
##I don't use cargo. And I don't know how it works. Support for this is VERY experimental
if test -f "$FILE_CARGO"; then
    echo -e $YELLOW"Updating Rust Packages (CARGO)..."$ENDCOLOR
    cargo update >/dev/null
    cargo fetch >/dev/null
    cargo fix >/dev/null
fi

#Update Zeek Packages if zkg is installed
##I don't use zkg, this could be made wrong, support for this is VERY experimental
if test -f "$FILE_ZKG"; then
    echo -e $YELLOW"Updating Zeek Packages (ZKG)..."$ENDCOLOR
    zkg upgrade >/dev/null
fi

#Update pips if pip3 is installed
if command -v pip3 &> /dev/null; then
    echo -e $YELLOW"Updating pips..."$ENDCOLOR
    sudo -u $NONSUDOUSER pip3 list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip3 install -U
fi

#Update LibreGaming packages if LibreGaming is Installed
if test -f "$FILE_LIBREGAMING"; then
    echo -e $YELLOW"Updating LibreGaming packages..."$ENDCOLOR
    LibreGaming --basic >/dev/null
fi

#Update Atom packages if Atom IDE is installed
if command -v apm &> /dev/null; then
    echo -e $YELLOW"Updating Atom IDE packages..."$ENDCOLOR
    apm upgrade -y >/dev/null
fi

#Update betterdiscordctl packages if betterdiscordctl is installed
if command -v betterdiscordctl &> /dev/null; then
    echo -e $YELLOW"Updating betterdiscordctl..."$ENDCOLOR
    sudo -u $NONSUDOUSER betterdiscordctl self-upgrade >/dev/null 2>&1
fi

#Update TLDR pages if TLDR is installed
if command -v tldr &> /dev/null; then
    echo -e $YELLOW"Updating TLDR pages..."$ENDCOLOR
    sudo -u $NONSUDOUSER tldr -u | grep -v --color=never "Successfully updated local database" | grep -v "Updated cache for"
fi

#Fix missing or broken dependencies (APT)
if test -f "$FILE_APTGET"; then
    echo -e $YELLOW"Fixing broken packages (APT)..."$ENDCOLOR
    apt-get -qq --fix-broken install -y
fi

#Empty trashes ##Doesn't support MacOS
echo -e $YELLOW"Emptying trashes..."$ENDCOLOR
rm -rf /home/*/.local/share/Trash/*/** &> /dev/null
rm -rf /root/.local/share/Trash/*/** &> /dev/null

#Remove useless stuff

#Clean with aptitude (if aptitude is installed)
if test -f "$FILE_APTITUDE"; then
    echo -e $YELLOW"Cleaning apt cache..."$ENDCOLOR
    aptitude clean >/dev/null

    echo -e $YELLOW"Removing old config files..."$ENDCOLOR
    aptitude purge $OLDCONF -y >/dev/null
fi

#Autoremove and clean around with APT
if test -f "$FILE_APTGET"; then
    echo -e $YELLOW"Autoremoving/Autocleaning/Autopurging (APT)..."$ENDCOLOR
    apt-get -qq autoremove -y --purge
    apt-get -qq autoclean -y
    apt-get -qq autopurge -y
    echo -e $YELLOW"Removing unnessesary configuration files (APT)..."$ENDCOLOR
    dpkg -l | grep "^rc" | awk '{print $2}' | sudo xargs dpkg --purge 2>/dev/null
    apt-get purge `dpkg --get-selections | grep deinstall | awk '{print $1}'` -qq
fi

#Autoremove with BREW
if test -f "$FILE_BREW"; then
    if [[ $(sudo -u $NONSUDOUSER brew autoremove -n) ]]; then
        echo -e $YELLOW"Autoremoving old packages (BREW)..."$ENDCOLOR
        sudo -u $NONSUDOUSER brew autoremove
    fi
    if [[ $(sudo -u $NONSUDOUSER brew cleanup -n) ]]; then
        echo -e $YELLOW"Removing stale install files (BREW)..."$ENDCOLOR
        sudo -u $NONSUDOUSER brew cleanup
    fi
fi

#Autoremove with PACMAN & YAY
if test -f "$FILE_PACMAN"; then
  if command -v yay &> /dev/null; then
    if [[ $(sudo -u $NONSUDOUSER yay -Qdtq) ]]; then
        echo -e $YELLOW"Removing orphaned packages (YAY)..."$ENDCOLOR
        pacman -R $(sudo -u $NONSUDOUSER yay -Qdtq) --noconfirm 1>/dev/null
    fi
    echo -e $YELLOW"Removing unused package cache (YAY)..."$ENDCOLOR
    sudo -u $NONSUDOUSER yay -Sc --noconfirm 1>/dev/null
    rm -rf /home/$NONSUDOUSER/.cache/yay/vcs.json
  else
    if [[ $(pacman -Qdtq) ]]; then
      echo -e $YELLOW"Removing orphaned packages (PACMAN)..."$ENDCOLOR
      pacman -R $(pacman -Qdtq) --noconfirm 1>/dev/null
    fi
    echo -e $YELLOW"Removing unused package cache (PACMAN)..."$ENDCOLOR
    pacman -Sc --noconfirm 1>/dev/null
  fi
fi

#Declare script end
echo -e $YELLOW"Script Finished!"$ENDCOLOR
